### ISSUE TITLE
Crashes when clicking "Run"

### ISSUE THREAD

**Issue by richardklingler** [AlwaysOfflineSoftware/XojoToAppImage#1]
Tried with a simple Xojo 2024r2.1 Linux project, and it crashes at:

`App.executableLocation.Parent.Child(App.executableLocation.Name+" Resources").CopyTo(binDir)
`

There is no Resources folder in the built project.

When I comment out that line, it crashes further down at:

`App.resourcesFolder.Child("AppRun").CopyTo(App.appDirFolder)
`

**Comment by hopelessdecoy** [comment]
I thought all projects had a resources folder by default, my mistake. I'll have a fix for this soon, until then please make a resources folder as a work around. I appreciate the bug report!

**Comment by hopelessdecoy** [comment]
There added a check to make sure the folder exists before trying to copy it. So shouldn't be an issue now.

#When I comment out that line, it crashes further down at:
#App.resourcesFolder.Child("AppRun").CopyTo(App.appDirFolder) 

Please make sure when you build this the Assets folder in the editor looks like this:
![image](https://github.com/user-attachments/assets/2343effa-c392-46d2-afe7-b7ef76e812a2)

I also have a Patreon with pre-built AppImages of everything I make for sale :)
https://www.patreon.com/AlwaysOfflineSoftware
